#!/usr/bin/env python -u

import argparse
from floater import utils

parser = argparse.ArgumentParser(
        description='Translate MITgcm mds float output files into pytables HDF format.')
        
parser.add_argument('--float_file_prefix', default='float_trajectories',
                    metavar='PREFIX',
                    help='prefix of MITgcm output files (e.g. float_trajectories.001.001.data)')
parser.add_argument('--float_buf_dim', default=14, metavar='N',
                    help='number of items in each trajectory record')      

parser.add_argument('--progress', dest='progress', action='store_true')
parser.set_defaults(feature=False)  
        
parser.add_argument('--input_dir', default='./', metavar='DIR',
                   help='directory in which to find the MITgcm float data')

parser.add_argument('output_file',
                   help='directory in which to find the MITgcm float data')


args = parser.parse_args()

utils.floats_to_tables(args.input_dir, args.output_file,
                        float_file_prefix=args.float_file_prefix,
                        fltBufDim=args.float_buf_dim,
			progress=args.progress)
